[build]
  command = "bundle exec jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"
  JEKYLL_VERSION = "4.2.0"
  RUBY_VERSION = "3.1.0"
  BUNDLER_VERSION = "2.4.0"

[[plugins]]
  package = "@netlify/plugin-jekyll"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true 